# Generated by Django 3.0 on 2020-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
