# Generated by Django 3.0 on 2020-02-11 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0008_auto_20200208_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('payment_method', models.IntegerField(choices=[(1, 'Cash on Delivery'), (2, 'Credit Card'), (3, 'Remittance')])),
                ('transaction_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Received'), (3, 'Declined')])),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
        ),
    ]
