# Generated by Django 3.0 on 2020-02-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200211_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Payment Received'), (3, 'Declined')]),
        ),
    ]
