# Generated by Django 3.0 on 2020-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200401_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
